name: dashed_color_circle
description: A fully customizable dashed color circle. You can add partial colors, change the style of the dashes and edit it however you wish.
version: 0.0.2
homepage: https://github.com/dbilgin/dashed_color_circle

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
